# Generated by Django 3.2.8 on 2021-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
