# Generated by Django 3.2.8 on 2021-11-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20211125_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
