# Generated by Django 3.2.8 on 2021-11-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20211125_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaid',
            name='group',
        ),
    ]
