# Generated by Django 3.2.8 on 2021-12-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_sale_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.group'),
        ),
    ]
