# Generated by Django 3.2.8 on 2021-12-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_remove_stock_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaid',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.group'),
        ),
    ]
