# Generated by Django 3.2.8 on 2021-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_alter_prepaid_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='email',
        ),
        migrations.AddField(
            model_name='invite',
            name='key',
            field=models.CharField(default='3nSsi3ncivi3v98b', max_length=16),
        ),
    ]
