# Generated by Django 3.2.8 on 2021-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_auto_20211210_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
